### ISSUE TITLE
Possible to access CLDR data from compiled formatters at runtime?

### ISSUE THREAD

**Issue by franktroia** [globalizejs/globalize-compiler#9]
Hi,

For a date input component, I'd like to provide some help text to the user indicating the date format the input component is expecting. I've compiled my formatters and parsers, thus I no longer seem to have access to the underlying CLDR data to get the date format. Or am I mistaken -- is there some way to access the underlying CLDR data associated with a compiled formatter/parser? I'd prefer not to have to load the CLDR data by itself to get this information.

I could conceive a similar problem with a currency input component as it would be useful to know the currency symbol and which side to place the currency symbol.

Thanks for all your hard work!

**Comment by rxaviers** [comment]
Hi @franktroia,

That's challenging, because the one of the goals with the compiled formatters and parsers is actually to get rid off CLDR. If your formatter/parser uses the data you're looking for, the data will be available at the `formatter/parser.runtimeArgs`, but that's very hacky. One suggestion is make the info you're looking for part of Globalize API. For example, something analogous to https://github.com/tc39/ecma402/issues/21.

Feel free to file an issue on Globalize with your suggested API.

Thanks
